[package]
name = "Outscale"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
rusqlite = { version = "0.34.0", features = ["bundled"]}
colored = "3.0.0"
crossterm = "0.29.0"
rand = "0.9.1"
serde = { version = "1.0.218", features = ["derive"] }